server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1GB #todo что по размеру в будущем?
      max-request-size: 1GB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://db:5432/lms?currentSchema=lms
    platform: postgres
    continue-on-error: true
    hikari:
      schema: lms
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: lms
    liquibase-schema: lms
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        generate_statistics: false
        default_schema: lms

minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: bucket-name #todo потом через апи сделать создание(тип бакет с модулем/хранением картинок ачивок)
  secure: false