FROM maven:latest AS build
WORKDIR /app

COPY ../pom.xml ./
RUN mvn dependency:go-offline

COPY ../src ./src

RUN mvn package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app

RUN apt-get update && apt-get install -y curl && apt-get clean

COPY --from=build /app/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]