FROM maven:latest AS build
WORKDIR /app

COPY ../pom.xml ./
RUN mvn dependency:go-offline

COPY ../src ./src

# Собираем приложение
RUN mvn package -DskipTests

# Финальный образ
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]